/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo2;

public class App {

    public static void main(String[] args) {
        Game game = new Game(4);
        game.start(10);
    }
}
