/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo2;

public class Card {
    private int rank;
    private Suit suit;

    // constructor
    public Card(int rank, Suit suit) {
        this.rank = rank;
        this.suit = suit;
    }

    // getters
    public int getRank() {
        return rank;
    }

    public Suit getSuit() {
        return suit;
    }

    public String toString() {
        return rank + " of " + suit;
    }

    public boolean compareTo(Card otherCard) {
        if (this.rank == otherCard.rank) {
            return this.suit.getValue() - otherCard.suit.getValue() > 0;
        } else {
            return this.rank - otherCard.rank > 0;
        }
    }
}
