/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.demo2;

import org.junit.Test;
import demo2.*;

import static org.junit.Assert.*;
import static org.junit.Assert.assertTrue;

public class CardTest {
    @Test
    public void testCard() {
        Card card = new Card(11, Suit.HEARTS);
        Card card2 = new Card(11, Suit.SPADES);
        assertEquals(11, card.getRank());
        assertEquals(Suit.HEARTS, card.getSuit());
        assertTrue(card2.compareTo(card));
        assertEquals(11 + " of " + Suit.SPADES, card2.toString());
        assertEquals(11 + " of " + Suit.HEARTS, card.toString());
    }
}
