/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.demo2;

import org.junit.Test;
import demo2.*;
import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertTrue;

public class DeckTest {

    @Test
    public void testShuffle() {
        Deck deck = new Deck();
        List<Card> initialCards = new ArrayList<>(deck.getCards());
        deck.shuffle();
        List<Card> shuffledCards = deck.getCards();
        assertNotEquals(initialCards, shuffledCards);
    }

    @Test
    public void testDealCards() {
        Deck deck = new Deck();
        ArrayList<Player> players = new ArrayList<>();
        int numberOfPlayers = 5;
        int numberOfCards = 10;
        for (int i = 0; i < numberOfPlayers; i++) {
            players.add(new Player("player" + i));
        }
        deck.dealCards(players, numberOfCards);
        for (Player player : players) {
            assertTrue(player.getHand().size() <= numberOfCards);
        }
    }
}
