/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.demo2;

import demo2.*;

import java.util.List;
import java.util.Map;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

public class GameTest {

    @Test
    public void testStart() {
        Game game = new Game(4);
        game.start(10);
        assertEquals(4, game.getPlayers().size());
        for (Player player : game.getPlayers()) {
            assertTrue(player.getHand().size() != 10);
        }
    }

    @Test
    public void testDetermineWinner() {
        Game game = new Game(4);
        game.start(10);
        game.determineWinner();
        Map<Player, Integer> scores = game.getScores();
        Player winner = null;
        int maxScore = Integer.MIN_VALUE;
        for (Player player : scores.keySet()) {
            if (scores.get(player) > maxScore) {
                winner = player;
                maxScore = scores.get(player);
            }
        }
        assertNotNull(winner);
        assertTrue(scores.get(winner) > 0);
    }
}