/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.demo2;

import org.junit.Test;
import demo2.*;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class PlayerTest {

    @Test
    public void testPlayCard() {
        Player player = new Player("player1");
        player.getHand().add(new Card(1, Suit.HEARTS));
        Card playedCard = player.playCard();
        assertNotNull(playedCard);
        assertEquals(Suit.HEARTS, playedCard.getSuit());
        assertEquals(1, playedCard.getRank());
        assertEquals(0, player.getHand().size());
    }

    @Test
    public void testPlayCardEmptyHand() {
        Player player = new Player("player1");
        Card playedCard = player.playCard();
        assertEquals(null, playedCard);
        assertEquals(0, player.getHand().size());
    }
}
