/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.demo2;

import org.junit.Test;
import demo2.*;

import static org.junit.Assert.assertEquals;

public class SuitTest {

    @Test
    public void testValueOfClubs() {
        Suit suit = Suit.CLUBS;
        assertEquals(1, suit.getValue());
    }

    @Test
    public void testValueOfDiamonds() {
        Suit suit = Suit.DIAMONDS;
        assertEquals(2, suit.getValue());
    }

    @Test
    public void testValueOfHearts() {
        Suit suit = Suit.HEARTS;
        assertEquals(3, suit.getValue());
    }

    @Test
    public void testValueOfSpades() {
        Suit suit = Suit.SPADES;
        assertEquals(4, suit.getValue());
    }
}